server:
  port: 8084


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    initial-size: 1
    min-idle: 1
    max-active: 20
      #获取连接等待超时时间
    max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20

DataSync:
  TEMP_DATA_DIR: /Users/messi/Desktop/ems1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.messiyang.modelreplace.model

